### ISSUE TITLE
om-welcome crashing on system without vulkan support

### ISSUE THREAD

**Issue by 0x041E** [OpenMandrivaAssociation/distribution#3355]
**OpenMandriva version**:
NAME="OpenMandriva Lx"
VERSION="25.06 (ROME) Rolling"
ID="openmandriva"
VERSION_ID="25.06"
PRETTY_NAME="OpenMandriva Lx 25.06 (ROME) Rolling"
BUILD_ID="20250605.11"
VERSION_CODENAME="rome"
ANSI_COLOR="1;43"
LOGO="openmandriva"
CPE_NAME="cpe:/o:openmandriva:openmandriva_lx:25.06"
HOME_URL="http://openmandriva.org/"
BUG_REPORT_URL="https://github.com/OpenMandrivaAssociation/distribution/issues/"
SUPPORT_URL="https://forum.openmandriva.org"
PRIVACY_POLICY_URL="https://www.openmandriva.org/tos"

installed fresh today from OpenMandrivaLx.rolling-snapshot.20250721.4095-plasma6wayland.x86_64.iso

**Describe the bug**:
Window of om-welcome briefly flashes and disappears. Running it from command line reveals that it's crashing due to missing Vulkan support of the GPU.

**Steps to reproduce**:
Install OpenMandriva ROME Plasma 6 Wayland on system that doesn't support Vulkan at all on any GPU. Laptop I installed on has Intel HD2000 paired with Nvidia GT635m. Nvidia card is using nouveau and is powered off. Intel igpu is using modesetting driver. Both cards have no support of vulkan at all but support at least Opengl 3.3

**Observed behavior**:
Crashes with following output when run in terminal:

QTWEBENGINE_FORCE_USE_GBM environment variable is set and it is for debugging purposes only.
GBM support is force disabled.
GBM is not supported with the current configuration. Fallback to Vulkan rendering in Chromium.
VULKAN: Failed to import memory object.
Aborted (core dumped)

**Expected behavior**:
Should end gracefully. Maybe even show an error popup to the user?

**Additional comment**:
This a low priority issue and most users probably won't run into this

**Logs and screenshots if relevant**
Screenshot of the terminal output
<img width="1154" height="683" alt="Image" src="https://github.com/user-attachments/assets/272e94cf-f372-4641-aa47-1dce774aebca" />

Coredump file
[core.htmlscript.1001.02072f7f8ea14fbdb78c64fb8cdfa472.24636.1757770161000000.tar.gz](https://github.com/user-attachments/files/22311094/core.htmlscript.1001.02072f7f8ea14fbdb78c64fb8cdfa472.24636.1757770161000000.tar.gz)

**Comment by AngryPenguinPL** [comment]
@berolinux  please take a look

**Comment by AngryPenguinPL** [comment]
I can confirm same issue.

**Comment by eNg1ne85** [comment]
The same behavior can be reproduced on virtual machine (qemu) with exactly same log.

**Comment by ZeroAbility** [comment]
>Install OpenMandriva ROME Plasma 6 Wayland on system that doesn't support Vulkan at all on any GPU. Laptop I installed on has Intel HD2000 paired with Nvidia GT635m. Nvidia card is using nouveau and is powered off. Intel igpu is using modesetting driver. Both cards have no support of vulkan at all but support at least Opengl 3.3

Because  you are using a hybrid VGA setup, please confirm if the issue occurs under these conditions:

* X11 version with `nouveau` in a single screen configuration
* X11 version with `nvidia` in a single screen configuration
* Wayland version with `nvidia` in a single screen configuration

Wayland with `nouveau` is pretty much a no-go for any sane testing.

Make sure your BIOS is up to date, and the discreet adapter is selected in BIOS as your primary VGA adapter.

**Comment by 0x041E** [comment]
> > Install OpenMandriva ROME Plasma 6 Wayland on system that doesn't support Vulkan at all on any GPU. Laptop I installed on has Intel HD2000 paired with Nvidia GT635m. Nvidia card is using nouveau and is powered off. Intel igpu is using modesetting driver. Both cards have no support of vulkan at all but support at least Opengl 3.3
> 
> Because you are using a hybrid VGA setup, please confirm if the issue occurs under these conditions:
> 
> * X11 version with `nouveau` in a single screen configuration
> * X11 version with `nvidia` in a single screen configuration
> * Wayland version with 'nvidia` in a single screen configuration
> 
> Wayland with `nouveau` is pretty much a no-go for any sane testing.
> 
> Make sure your BIOS is up to date, and the discreet adapter is selected in BIOS as your primary VGA adapter.

Hybrid gpu doesn't seem to be the issue because I've ran into the exact same issue on a single gpu laptop having the same intel HD 2000 igpu.

On the original hybrid gpu laptop where i found the issue I cannot test these setups because it is a muxless laptop with display hardwired to igpu with no bios gpu selection and wayland is out of question because last supported nvidia proprietary driver for the card is 390. That's the whole reason why i use nouveau for the card to just keep it turned off and use only intel one. I can also use acpi_call to power off the nvidia card and completely remove it from the system where even `lspci` won't show it but that does not fix the crashing issue.

**Comment by 0x041E** [comment]
And a desktop PC with Nvidia Geforce 210 Rev. 2.0 which is also OpenGL only card can reproduce the same issue as well on the X11 plasma image of ROME.

<img width="1496" height="868" alt="Image" src="https://github.com/user-attachments/assets/84328e88-df6d-4d3d-b773-789cd795d926" />

**Comment by AngryPenguinPL** [comment]
We can confirm. This bug is also in Cooker and also affects AMD Radeon RX chipsets with the Mesa driver on x11 and Wayland.

**Comment by ZeroAbility** [comment]
It works when I open it, but crashes when I change to a different tab. Maybe it just needs to be rebuilt.

It appears to just be a series of scripts, so rebuilding might not help.

https://github.com/OpenMandrivaSoftware/om-welcome

**Comment by ZeroAbility** [comment]
It appears this was fixed in Cooker.

**Comment by eNg1ne85** [comment]
Still an issue on qemu virtual machine, which doesn't have Vulkan support:
```
[engine@openmandriva-x8664 ~]$ om-welcome
QTWEBENGINE_FORCE_USE_GBM environment variable is set and it is for debugging purposes only.
GBM support is force disabled.
GBM is not supported with the current configuration. Fallback to Vulkan rendering in Chromium.
VULKAN: Failed to import memory object.
Aborted                    (core dumped) om-welcome
```

**Comment by ZeroAbility** [comment]
Did you `dsync` Cooker?

**Comment by eNg1ne85** [comment]
> Did you `dsync` Cooker?

Yes, I have verified that with up to date Cooker on 2 VM in qemu (on different PCs).

**Comment by AngryPenguinPL** [comment]
ok, so it would be good to try to debug it somehow...
The problem is that I was experiencing a crash even with Vulkan support. After the latest fixes, I no longer have this crash. I'll try launching Qemu and tinkering around a bit.

**Comment by eNg1ne85** [comment]
Latest Cooker version seems to fix this issue for me, tested in qemu VM machine without vulkan support.
